//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Xml;
using System.Collections.Generic;
using UnityEngine;
using ArabicSupport;
using System.Text.RegularExpressions;

namespace CoreLib
{
	public class ContentManager : MonoSingleton<ContentManager>
	{
		private IContentManager contentMan;

		public ContentManager ()
		{			
			#if CLIENT_BUILD
			contentMan = new ContentManagerClient();
			#else
			contentMan = new ContentManagerDummy();
			#endif
		}

		protected override void Init(){}
		   
		public string getString( string id, string languageInitials="" )
		{
			return contentMan.getString (id, languageInitials);
		}

        public string FormatArabicString(string arabicText)
        {
			return contentMan.FormatArabicString (arabicText);
        }
    }
}

